CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  user VARCHAR(100) NOT NULL,
  book VARCHAR(150) NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);